[package]
name = "tdigest"
version = "1.0.1"
authors = ["Jim Cooke <jim.cooke.aus@gmail.com>"]

[lib]
name = "tdigest"

[[bin]]
name = "tdigest"

[dependencies]
quickersort = { git = "https://github.com/young-zhang/quickersort.git", branch="master" }
serde_json = "1.0"
